### ISSUE TITLE
Make the base URL configurable

### ISSUE THREAD

**Issue by netbrothers-tr** [cronkeep/cronkeep#28]
CronKeep currently cannot run in an URL alias or subdirectory such as www.example.com/cronkeep/.

**Comment by bogdanghervan** [comment]
Just tried setting it up as an alias, and while I got the index page to show up, everything else is broken. I'll look into it.

Thank you for the report.

**Comment by netbrothers-tr** [comment]
Hi @bogdanghervan, thank you for checking this out. For instance, take a look at https://github.com/cronkeep/cronkeep/blob/master/src/assets/js/crontab.js#L31. You can see that the URL in the AJAX call is relative (`"/job/run"`, no domain name is there), but this only works, if your application sits right in the root path of the domain, i.e. is accessible via `"/"`. One way to solve this issue is to generate the correct AJAX URL dynamically on the server side (maybe by using a base URL configuration option) and print it into the view (as a hidden field or an attribute of the button for example). The other way to solve this would be to have the responding script within the same path as the viewed page. But I'm not sure about which one of those two options is the easiest to implement with the Slim framework.

**Comment by micschk** [comment]
+1 The base URL not being configurable also prevents this tool from being included as part/module into existing projects.

**Comment by micschk** [comment]
It seems just changing all JS ajax URLs to be relative makes running in a subdirectory work. I'm working a SilverStripe module which includes a (modified) version of CronKeep in a subdir. If you'd like, I can PR my edits.

**Comment by bogdanghervan** [comment]
Fixed this issue by detecting the base URL and prepending it to all AJAX calls and static resources (tag v0.1.2).

For Apache users, `RewriteBase` should be updated accordingly in `.htaccess`. For instance, if you're running CronKeep at http://www.example.com/cronkeep, the configuration directive needs to look like this:
```Apache
RewriteBase /cronkeep
```

I will update the docs to reflect this scenario as well, but in the meantime please let me know if this works for you.

**Comment by micschk** [comment]
Hi @bogdanghervan, thanks for fixing. 
However, I wonder why you prefer this approach over simply making the ajax urls relative (which seems to work fine), perhaps combined with a base href tag if prefered.
The problem I see with having to edit the .htaccess, is that these changes will be overridden when you update from git/composer.

BTW; I've adapted CronKeep for inclusion in the SilverStripe framework as a dev-task: https://github.com/restruct/silverstripe-cronkeep

Thanks for this simple & great tool!
