### ISSUE TITLE
www-data is not allowed to use this program (crontab)

### ISSUE THREAD

**Issue by Smtgr14** [cronkeep/cronkeep#30]
I cannot seem to get www-data access to the crontab command.
I've added an entry to the sudoers file:
`www-data ALL=(ALL)NOPASSWD:/usr/bin/crontab`
Yet it still throws the same error. Am I missing something?

**Comment by Smtgr14** [comment]
My mistake, I forgot to add www-data to the cron.allow file.

Can you include this in the install instructions?

**Comment by bogdanghervan** [comment]
Sure thing. Could you tell me what Linux system your CronKeep installation runs on? Is it a vanilla installation?

**Comment by Smtgr14** [comment]
Ubuntu 16.04

**Comment by bogdanghervan** [comment]
Now CronKeep recognizes this error and suggests that the user go to the [Troubleshooting](https://github.com/cronkeep/cronkeep/blob/master/INSTALL.md#you-www-data-are-not-allowed-to-use-this-program-crontab) section for recommendations to fix it.
