### ISSUE TITLE
See crontab(1) for more information

### ISSUE THREAD

**Issue by mrsegen** [cronkeep/cronkeep#31]
After installing via composer on a Linux (Debian Jesse) server, I went to http://[host]/cronkeep/src/ in a browser. I received the following error:
`There has been an error reading the crontab. Here's the output from the shell: You (daemon) are not allowed to use this program (crontab) See crontab(1) for more information`

Where is `crontab(1)`? I couldn't find anything in the Wiki to help.

**Comment by bogdanghervan** [comment]
CronKeep uses the standard `crontab` utility for reading and writing cron jobs. `crontab(1)` is just a reference to the manual page (run `man crontab` from a Linux shell to read it).

The user `daemon` is probably denied access from a file called `/etc/cron.deny` which blacklists users, one per line - you may remove the line "daemon" from there to allow access. Here's an excerpt from `crontab`'s manual:
> If the /etc/cron.allow file exists, then you must  be  listed  (one  user  per  line) therein in order to be allowed to use this command.  If the /etc/cron.allow file does not exist but the /etc/cron.deny file does exist, then you must not be listed in the /etc/cron.deny file in order to use this command.

The manual also states that:
> For standard Debian systems, all users may use this command.

Sorry for the delay in replying. Let me know if you need more help and I'll be here to assist you!
