### ISSUE TITLE
sh: 1: at: not found

### ISSUE THREAD

**Issue by imrantune** [cronkeep/cronkeep#32]
I have just installed cronkeep getting this error 
on Ubuntu 16.04

`Oh Snap!

at is not available on this system. CronKeep uses this slick command internally to run jobs independently from your web server, whenever you hit "Run". This means you could restart your web server and still have the process running in the background.
Here's the raw output from the command that may help you debug this further:
sh: 1: at: not found`

**Comment by bogdanghervan** [comment]
Hey @imrantune,

The message you are seeing is merely a warning that the `at` command is missing from your Ubuntu installation. `at` is a standard utility found in Unix-like operating systems used to schedule commands to run once at a particular time in the future.

CronKeep uses it behind the scenes to run your jobs whenever you the hit the "Run" button, but when `at` is not available it detects that that's the case and fallbacks to invoking the command directly with the downside that if you need to restart your web server and the command is still running, it will be stopped as well (which is what we try to avoid by nicely asking `at` to run it for us).

You can either install `at` or dismiss the warning for 3 days (and still be able to use CronKeep just fine). To install `at`:
* Confirm that you don't have it already:
```Shell
$ dpkg --list at
dpkg-query: no packages found matching at
```
* Then you can install like so:
```Shell
apt-get install at
```
* You can now see that you have it:
```Shell
$ dpkg --list at
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  at                      3.1.18-2ubuntu1  amd64            Delayed job execution and batch processing
```
* Refresh CronKeep and enjoy a warning-free experience :)

Let me know if this worked and if you need more help setting things up.

**Comment by myatmins** [comment]
I've already installed at, removed www-data from at.deny and still happing this

![image](https://user-images.githubusercontent.com/6258919/46125912-28f3b580-c251-11e8-9946-28aa777e6414.png)
