### ISSUE TITLE
Error on editing and can't add new job

### ISSUE THREAD

**Issue by nico7576** [cronkeep/cronkeep#34]
Hi,

Recently installed cronkeep on my Raspberry Pi and seems to be perfect for my need.
But I can't add or edit any cron job.
I have the home page, I see a job created manually but can't edit it. I've the error message "CloseUnable to edit the job at this time". In the console, I've an 404 error on the requested page : http://192.168.0.31/job/edit-form/7677c207

If I try to add a new job, the saving button seems always checked after click. And no new job in the crontab.

Tested with Firefox 50.1.0 and Vivaldi 1.6.689.34

Regards,
Nicolas

**Comment by bogdanghervan** [comment]
Hi Nicolas,

It's great to hear that CronKeep made its way to a Raspberry Pi!

It looks as though you might be seeing issue #29. Can you go through these steps first and let me know if it fixes your problem?

> 1. Make sure Apache's `mod_rewrite` is enabled;
> 2. Make sure `AllowOverride all` is enabled inside the virtual host definition ([example](https://github.com/cronkeep/cronkeep/blob/master/provision/ubuntu/virtual-host.conf)). This is so that directives in `src/.htaccess` would be taken into account by Apache;
> 3. Restart Apache;

Similar steps would apply to nginx as well (you would need to create a server block for CronKeep - let me know if you need more help with that).

Thanks.

**Comment by nico7576** [comment]
Hi

Thank you verry much for your answer !
Everything is now OK. Cronkeep is THE cron manager I was looking for.

Thank you !!!
Nicolas

**Comment by nico7576** [comment]
Hi

FYI, i've just made a fresh install of my RPi in order to install lighttpd instead of appache and it's OK

Just modify /etc/lighttpd/lighttpd.conf to add mod_rewrite module and add this because there's no .htaccess with lighttpd :

`url.rewrite-once = (
    ".*\?(.*)$" => "/index.php?$1",
    ".*\.(js|ico|gif|jpg|png|swf|css|html|woff|ttf|ico)$" => "$0",
    "" => "/index.php"
)`

**Comment by bogdanghervan** [comment]
Nicolas, great to hear everything worked!

**Comment by rileycoyote87** [comment]
Hi Nico7576 I was wondering how you setup cronkeep with lighttpd. I'm having some issues.

**Comment by Micha-Btz** [comment]
@nico7576  can you please post your config with lighttpd?
On my raspi I can't edit, pause or delete jobs for www-data. On bash with crontab -e it works.
If I add your rewrite rule, nothing works more. :-)

> 548093743|dietpi|GET /cronkeep/src/ HTTP/1.1|200|33290
> 1548093743|dietpi|GET /cronkeep/src/assets/css/bootstrap.min.css HTTP/1.1|200|18137
> 1548093743|dietpi|GET /cronkeep/src/assets/css/styles.css HTTP/1.1|200|1724
> 1548093743|dietpi|GET /cronkeep/src/assets/js/jquery-1.11.1.min.js HTTP/1.1|200|33266
> 1548093743|dietpi|GET /cronkeep/src/assets/js/jquery.validate.min.js HTTP/1.1|200|6756
> 1548093743|dietpi|GET /cronkeep/src/assets/js/bootstrap.min.js HTTP/1.1|200|8536
> 1548093743|dietpi|GET /cronkeep/src/assets/js/highlightRegex.min.js HTTP/1.1|200|742
> 1548093743|dietpi|GET /cronkeep/src/assets/js/alert.js HTTP/1.1|200|844
> 1548093743|dietpi|GET /cronkeep/src/assets/js/crontab.js HTTP/1.1|200|1819
> 1548093743|dietpi|GET /cronkeep/src/assets/js/job-add.js HTTP/1.1|200|3733
> 1548093743|dietpi|GET /cronkeep/src/assets/js/search.js HTTP/1.1|200|1738
> 1548093743|dietpi|GET /cronkeep/src/assets/js/index.js HTTP/1.1|200|678
> 1548093743|dietpi|GET /cronkeep/src/assets/fonts/glyphicons-halflings-regular.woff HTTP/1.1|200|23320
> 1548093745|dietpi|GET /cronkeep/src/job/edit-form/d9625956 HTTP/1.1|404|345
> 1548093748|dietpi|GET /cronkeep/src/job/pause/d9625956 HTTP/1.1|404|345
> 1548093750|dietpi|GET /cronkeep/src/job/delete/d9625956 HTTP/1.1|404|345

I wloud like to use lighttpd, because pihole is runnung with it. Any hints @rileycoyote87 ?

TIA Micha
